---
- name: Build and push docker image...
  hosts: img-builder
  vars:
    dockerhubuser: viklosh
    dockerhubtoken: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          32336638386631306461386134393535616261356165656264646539383539303530333939383831
          6666393361313532393532303665643264376439643364300a343761333535653939653239326565
          30373030663932653235316538353632363536376138623735656163323135613330306164616639
          6164343835326531660a333363356166323734626331383362353939333662333236343366333135
          65383033666361343336666564333337336236333163363163356163353363653435343135383964
          3430326166396264313833393534366331643837383866653363
    dockerhubemail: xcodemail@mail.ru
    imagename: viklosh/boxfuse:latest

  become: yes

  tasks:
    
  - name: Ensure docker and python pip package is present.
    apt:
      name:
      - docker.io
      - python-pip
      update_cache: yes
      state: present

  - name: Ensure pip docker-py is present
    pip:
      name: docker-py

  - name: Create build directory
    file:
      path: ~/app
      state: directory
      owner: root
      group: root
      mode: '0755'

  - name: Copy Dockerfile
    copy:
      src: ./Dockerfile
      dest: ~/app
      owner: root
      group: root
      mode: '0644'

  - name: Log into DockerHub
    docker_login:
      username: '{{ dockerhubuser }}'
      password: '{{ dockerhubtoken }}'
      email: '{{ dockerhubemail }}'

  - name: Build an image and push it to docker hub.
    docker_image:
      path: ~/app
      name: '{{ imagename }}'
      push: yes

- name: Deploy boxfuse application...
  hosts: web
  become: yes

  tasks:
  - name: Ensure docker, python-pip package is present.
    apt:
      name:
      - docker.io
      - python-pip
      update_cache: yes
      state: present

  - name: Ensure pip docker-py is present
    pip:
      name: docker-py

  - name: Log into DockerHub
    docker_login:
      username: '{{ dockerhubuser }}'
      password: '{{ dockerhubtoken }}'
      email: '{{ dockerhubemail }}'
  
  - name: Ensure boxfuse container is started...
    docker_container:
      name: boxfuse
      image: '{{ imagename }}'
      state: started
      restart_policy: unless-stopped
      ports:
      - "8080:8080"